[apache_servers]
dunas-moodle     ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_dunas }}"
romeirao         ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_romeirao }}"
mangueirao       ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_mangueirao }}"
almoxarifado     ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_almoxarifado }}"

[nginx_servers]
coliseu-sonar    ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_coliseu }}"
parambu          ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_parambu }}"

[docker_servers]
alfredao-traefik ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_alfredao }}"
marizao-gitlab   ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_marizao }}"
independencia-haproxy ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_independencia }}"

[outros]
email-iredmail   ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_email }}"
colina-vpl       ansible_host=IP_AQUI ansible_user=USER_AQUI ansible_become_password="{{ senha_colina }}"

[servidores:children]
apache_servers
nginx_servers
docker_servers
outros
