[apache_servers]
dunas-moodle ansible_host=IP_AQUI
romeirao ansible_host=IP_AQUI
mangueirao ansible_host=IP_AQUI
almoxarifado ansible_host=IP_AQUI

[nginx_servers]
coliseu-sonar ansible_host=IP_AQUI
parambu ansible_host=IP_AQUI

[docker_servers]
alfredao-traefik ansible_host=IP_AQUI
marizao-gitlab ansible_host=IP_AQUI
independencia-haproxy ansible_host=IP_AQUI

[outros]
email-iredmail ansible_host=IP_AQUI
colina-vpl ansible_host=IP_AQUI

[servidores:children]
apache_servers
nginx_servers
docker_servers
outros
