[apache_servers]
# Substitua pelo usuário real de cada servidor (ex: root, admin, ufc)
dunas-moodle     ansible_host=IP_AQUI ansible_user=USER_AQUI
romeirao         ansible_host=IP_AQUI ansible_user=USER_AQUI
mangueirao       ansible_host=IP_AQUI ansible_user=USER_AQUI
almoxarifado     ansible_host=IP_AQUI ansible_user=USER_AQUI

[nginx_servers]
coliseu-sonar    ansible_host=IP_AQUI ansible_user=USER_AQUI
parambu          ansible_host=IP_AQUI ansible_user=USER_AQUI

[docker_servers]
alfredao-traefik ansible_host=IP_AQUI ansible_user=USER_AQUI
marizao-gitlab   ansible_host=IP_AQUI ansible_user=USER_AQUI
independencia-haproxy ansible_host=IP_AQUI ansible_user=USER_AQUI

[outros]
email-iredmail   ansible_host=IP_AQUI ansible_user=USER_AQUI
colina-vpl       ansible_host=IP_AQUI ansible_user=USER_AQUI

[servidores:children]
apache_servers
nginx_servers
docker_servers
outros
